# Generated by Django 4.1.5 on 2023-01-16 09:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.ImageField(upload_to=models.CharField(max_length=50))),
                ('img_url2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_url3', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_url4', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_url5', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_description', models.TextField(default='add short_description')),
                ('description', models.TextField(help_text='ex./n colour:red/n size:3 units ')),
                ('price', models.FloatField()),
                ('gst_price', models.FloatField()),
                ('type', models.CharField(choices=[('GW', 'Grinding wheel'), ('HG', 'Hand gloves'), ('SE', 'Safety equipments')], max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.CharField(max_length=12, unique=True)),
                ('Address_line1', models.CharField(max_length=100)),
                ('Address_line2', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
    ]
